export const fields  = [
// {
//     "headerName" : "",
//     "field": "selected",
//     "sortable": true,
//     "menuTabs": [],
//     "resizable": false,
//     "filter": true,
//     "suppressColumnsToolPanel": true,
//     "suppressFiltersToolPanel": true,
//     "hide" : true,
//     "width": 60,
//     "checkboxSelection": true
//   },
{
    "headerName" : "Photo",
    "autoHeight": true,
    // "wrapText":true,
    "field": "photo",
    "sortable": true,
    "sort": 'desc',
    "cellRenderer": "photoRender"
  },
{
    "headerName" : "Applicant Name",
    "field": "Applicant Name",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
  {
    "headerName" : "E-mail",
    "autoHeight": true,
    // "wrapText":true,
    "field": "email",
    "sortable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "resizable": true,
    "hide" : false,
  },
{
    "headerName" : "Cell Phone #",
    "field": "Cell Phone #",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Most Recent Medical School",
    "field": "Most Recent Medical School",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
  {
    "headerName" : "Most Recent Application Status",
    "field": "Most Recent Application Status",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Most Recent Application Status Date",
    "field": "Most Recent Application Status Date",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Tracks Considered by Program",
    "field": "Tracks Considered by Program",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Tracks Applied by Applicant",
    "field": "Tracks Applied by Applicant",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "USMLE Step 1 Score",
    "field": "USMLE Step 1 Score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
   {
    "headerName" : "USMLE Step 2 CK Score",
    "field": "USMLE Step 2 CK Score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
   {
    "headerName" : "USMLE Step 2 CS Score",
    "field": "USMLE Step 2 CS Score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
   {
    "headerName" : "COMLEX-USA Level 1 Score",
    "field": "COMLEX-USA Level 1 Score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
   {
    "headerName" : "COMLEX-USA Level 2 CE Score",
    "field": "COMLEX-USA Level 2 CE Score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "COMLEX-USA Level 2 PE Score",
    "field": "COMLEX-USA Level 2 PE Score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
 {
    "headerName" : "Rank",
    "autoHeight": true,
    // "wrapText":true,
    "field": "rank",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
    "editable": false,
    "cellRenderer": 'agGroupCellRenderer',
  },
  {
    "headerName" : "Manual Rank",
    "autoHeight": true,
    // "wrapText":true,
    "field": "manual_rank",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
    "editable": false
  },
  {
    "headerName" : "Pre-Interview Score",
    "autoHeight": true,
    // "wrapText":true,
    "field": "preinterview_score",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
    "editable": false
  },
  {
    "headerName" : "Status",
    "autoHeight": true,
    // "wrapText":true,
    "field": "status",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
    // "width": 100
  },
  {
    "headerName" : "AAMC ID",
    "autoHeight": true,
    // "wrapText":true,
    "field": "aamcid",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  
  {
    "headerName" : "AAMC ID",
    "autoHeight": true,
    // "wrapText":true,
    "field": "AAMC ID",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Alpha Omega Alpha (Yes/No)",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Alpha Omega Alpha (Yes/No)",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "application",
    "autoHeight": true,
    // "wrapText":true,
    "field": "application",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Citizenship",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Citizenship",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Complete Application Date",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Complete Application Date",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact Address 1",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Contact Address 1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact Address 2",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Contact Address 2",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact City",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Contact City",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact State",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Contact State",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact Zip",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Contact Zip",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Couples - Partner Name",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Couples - Partner Name",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Couples - Partner Specialty",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Couples - Partner Specialty",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Date of Birth",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Date of Birth",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "date_created",
    "autoHeight": true,
    // "wrapText":true,
    "field": "date_created",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "date_modified",
    "autoHeight": true,
    // "wrapText":true,
    "field": "date_modified",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Explanation of why Medical Education or Training Interrupted",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Explanation of why Medical Education or Training Interrupted",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "First Name",
    "autoHeight": true,
    // "wrapText":true,
    "field": "first name",
    "sortable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "resizable": true,
    "hide" : true,
    // "width": 100
  },
  {
    "headerName" : "Hobbies and Interests",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Hobbies and Interests",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Last Name",
    "autoHeight": true,
    // "wrapText":true,
    "field": "last name",
    "sortable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "resizable": true,
    "hide" : true,
    // "width": 100
  },
  {
    "headerName" : "Comments",
    "autoHeight": true,
    // "wrapText":true,
    "field": "comments",
    "sortable": true,
    "resizable": true,
    "menuTabs": ["filterMenuTab" ,"columnsMenuTab"],
    "filter": "agTextColumnFilter",
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
    "editable": false,
    "cellRenderer": "commentsRender",
    // "width": 350
  },
  {
    "headerName" : "Limitations Description",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Limitations Description",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Limiting Factors",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Limiting Factors",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical Education or Training Interrupted",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Medical Education or Training Interrupted",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School Degree Date of Graduation",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Medical School Degree Date of Graduation",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School Degree Date of Graduation_1",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Medical School Degree Date of Graduation_1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School of Graduation",
    "autoHeight": true,
    // "wrapText":true,
    "field": "medical school",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School of Graduation_1",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Medical School of Graduation_1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Organization",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Organization",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Participating as a Couple in NRMP",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Participating as a Couple in NRMP",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Preferred Phone",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Preferred Phone",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Rank-Term",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Rank-Term",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Total Interview Score",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Total Interview Score",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Tracks Applied by Applicant",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Tracks Applied by Applicant",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Tracks Applied by Applicant_1",
    "autoHeight": true,
    // "wrapText":true,
    "field": "Tracks Applied by Applicant_1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "USMLE Step 1 Score",
    "autoHeight": true,
    // "wrapText":true,
    "field": "USMLE Step 1 Score",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "USMLE Step 2 CK Score",
    "autoHeight": true,
    // "wrapText":true,
    "field": "USMLE Step 2 CK Score",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "uuid",
    "autoHeight": true,
    // "wrapText":true,
    "field": "uuid",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Actions",
    "autoHeight": true,
    // "wrapText":true,
    "field": "",
    "sortable": false,
    "resizable": true,
    "filter": false,
    "hide" : true,
    "suppressColumnsToolPanel": true,
    "suppressFiltersToolPanel": true,
    "cellRenderer": "actionsRender",
    "hide" : true,
    "width": 375

  },
]