export const fields  = [
{
    "headerName" : "",
    "field": "selected",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": false,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
    "width": 60,
    "checkboxSelection": true
  },
  {
    "headerName" : "AAMC ID",
    "field": "aamcid",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Photo",
    "field": "photo",
    "sortable": true,
    "sort": 'desc',
    // "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    // "resizable": true,
    // "filter": true,
    // "suppressColumnsToolPanel": false,
    // "suppressFiltersToolPanel": false,
    // "hide" : false,
    "cellRenderer": "photoRender"
  },
  {
    "headerName" : "AAMC ID",
    "field": "AAMC ID",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Alpha Omega Alpha (Yes/No)",
    "field": "Alpha Omega Alpha (Yes/No)",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "application",
    "field": "application",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Citizenship",
    "field": "Citizenship",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Complete Application Date",
    "field": "Complete Application Date",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact Address 1",
    "field": "Contact Address 1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact Address 2",
    "field": "Contact Address 2",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact City",
    "field": "Contact City",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact State",
    "field": "Contact State",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Contact Zip",
    "field": "Contact Zip",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Couples - Partner Name",
    "field": "Couples - Partner Name",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Couples - Partner Specialty",
    "field": "Couples - Partner Specialty",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Date of Birth",
    "field": "Date of Birth",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "date_created",
    "field": "date_created",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "date_modified",
    "field": "date_modified",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "E-mail",
    "field": "E-mail",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
  {
    "headerName" : "Explanation of why Medical Education or Training Interrupted",
    "field": "Explanation of why Medical Education or Training Interrupted",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "First Name",
    "field": "First Name",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
  {
    "headerName" : "Hobbies and Interests",
    "field": "Hobbies and Interests",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Last Name",
    "field": "Last Name",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
  {
    "headerName" : "Limitations Description",
    "field": "Limitations Description",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Limiting Factors",
    "field": "Limiting Factors",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical Education or Training Interrupted",
    "field": "Medical Education or Training Interrupted",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School Degree Date of Graduation",
    "field": "Medical School Degree Date of Graduation",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School Degree Date of Graduation_1",
    "field": "Medical School Degree Date of Graduation_1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Medical School of Graduation",
    "field": "Medical School of Graduation",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : false,
  },
  {
    "headerName" : "Medical School of Graduation_1",
    "field": "Medical School of Graduation_1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Organization",
    "field": "Organization",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Participating as a Couple in NRMP",
    "field": "Participating as a Couple in NRMP",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Preferred Phone",
    "field": "Preferred Phone",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Rank-Term",
    "field": "Rank-Term",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Total Interview Score",
    "field": "Total Interview Score",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Tracks Applied by Applicant",
    "field": "Tracks Applied by Applicant",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "Tracks Applied by Applicant_1",
    "field": "Tracks Applied by Applicant_1",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "USMLE Step 1 Score",
    "field": "USMLE Step 1 Score",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "USMLE Step 2 CK Score",
    "field": "USMLE Step 2 CK Score",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
  {
    "headerName" : "uuid",
    "field": "uuid",
    "sortable": true,
    "menuTabs": ["generalMenuTab", "filterMenuTab" ,"columnsMenuTab"],
    "resizable": true,
    "filter": true,
    "suppressColumnsToolPanel": false,
    "suppressFiltersToolPanel": false,
    "hide" : true,
  },
]